name: Deploy Beta Website

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test NPM Package Access
        run: curl -I https://registry.npmjs.org/camelcase-css/-/camelcase-css-2.0.1.tgz

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Use beta HTML + meta files
        run: |
          cp public/index-beta.html public/index.html
          cp public/robots-beta.txt public/robots.txt
          cp public/sitemap-beta.xml public/sitemap.xml

      - name: Build React App
        run: |
          echo "REACT_APP_EMAILJS_SERVICE_ID=${{ secrets.REACT_APP_EMAILJS_SERVICE_ID }}" >> .env
          echo "REACT_APP_EMAILJS_TEMPLATE_ID=${{ secrets.REACT_APP_EMAILJS_TEMPLATE_ID }}" >> .env
          echo "REACT_APP_EMAILJS_USER_ID=${{ secrets.REACT_APP_EMAILJS_USER_ID }}" >> .env
          npm run build

      - name: Upload to FTP
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "./build"
          remoteDir: "/beta"
